### ISSUE TITLE
Regex error in log files

### ISSUE THREAD

**Issue by ventilator** [vookimedlo/OctoPrint-Prusa-Mini-ETA#4]
Hi,
when I look at my log files, I see an SyntaxError from your plugin:
Should I be concerned?
System: up to date Octoprint on a OctoPi System on an RPI3. 
Important info: This is an offline installation without internet connection. Maybe its related to the error

2020-11-27 16:10:13,644 - octoprint.plugin.core - ERROR - Invalid syntax in /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_prusa_mini_eta/__init__.py for plugin prusa_mini_eta
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/plugin/core.py", line 599, in _parse_metadata
    root = ast.parse(f.read(), filename=path)
  File "/usr/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_prusa_mini_eta/__init__.py", line 35
    _remaining_time_pattern: Pattern[str] = re.compile(r'R(\d+)$')
                           ^
SyntaxError: invalid syntax

**Comment by vookimedlo** [comment]
Hi there,

I see you use the Python 2.7, which is not supported by my plugin. You need to use the Python 3.x.

```
File "/usr/lib/python2.7/ast.py", line 37, in parse
```
